### ISSUE TITLE
Question: Create NuGet package, configure options in DI

### ISSUE THREAD

**Issue by seangwright** [kentico-ericd/xperience-core-breadcrumbs#2]
Eric,

Cool Widget!

What are your thoughts on creating a public NuGet package from this?

If this was available as a package, it might be nice to configure the settings for the Widget to be supplied via DI and configured in `Startup.cs` through the standard extension method pattern.

It would also be nice for all the classes to be customizable (ex: `breadcrumb-item breadcrumb-current-page`).

I'd be happy to make a PR to add these if you are interested.

**Comment by kentico-ericd** [comment]
Hey @seangwright 😃 

Thanks for the feedback! I will eventually package this into NuGet and configuring the widget via DI is a good idea 👍 I'll also add more customization options.

Feel free to submit a PR if you'd like though!

**Comment by kentico-ericd** [comment]
@seangwright, I've added the ability to register properties via DI- can you take a look and see if it meets what you had in mind?

Regarding the extra CSS classes, can I ask what the motivation for that is? If you can control the classes of the surrounding container, you can already style all of the other elements on a per-widget basis.. why do you need to customize these?

**Comment by seangwright** [comment]
@kentico-ericd Ya, that's along the lines of what I was thinking.

I don't know what the asp.net community's conventions are, but I've also seen the pattern with the `Action<T>` in the extension method:

```csharp
public static class BreadcrumbsWidgetServiceExtensions
{
        public static void AddBreadcrumbs(this IServiceCollection services, Action<BreadcrumbsWidgetProperties> configure = null)
        {
            services.AddSingleton<BreadcrumbHelper>();
			var props = new BreadcrumbsWidgetProperties().Defaults();

            if (configure is object)
            {
                configure(props);
            }

            services.AddSingleton(props);
        }
}
```

This would be called like:

```csharp
services.AddBreadcrumbs();
```

or:

```csharp
services.AddBreadcrumbs(properties =>
{
    properties.Separator = ">>";
    properties.ShowContainers = false;
});
```

In regards to customizing all the classes, it's really not absolutely necessary, however any time a component/library includes classes in markup, those classes become part of the 'global' class 'namespace' in a way.

Which means a team needs to be sure to either _not_ use those classes accidentally, or use them explicitly how they are supposed to be used.

If they are using a BEM, SMACSS, or utility CSS (like TailwindCSS) approach to their CSS classes, the hardcoded classes might not match their conventions.

Again, this isn't required, but I could see how having the classes you are currently using as defaults in the `BreadcrumbsWidgetProperties` that could be overridden might be a nice enhancement for some teams.

**Comment by kentico-ericd** [comment]
@seangwright Thanks for all the help! I implemented the Action instead since it offers more flexibility. I also created a way to completely customize the rendering via DI and 2 new CSS classes. I think we can close this but let me know if you have anything else :)

**Comment by seangwright** [comment]
@kentico-ericd Ya, those updates look awesome. I like the custom renderer too.

Thanks for making this project. I look forward to using it in my sites!
