### ISSUE TITLE
First Breadcrumb

### ISSUE THREAD

**Issue by mattksand** [kentico-ericd/xperience-core-breadcrumbs#3]
Right now the first breadcrumbs brings back the site name or site title. But I don't see a way to change that name to be link "Home"

**Comment by kentico-ericd** [comment]
Hey @mattksand!

You could alter the way the first breadcrumb item displays using a [custom renderer](https://github.com/kentico-ericd/xperience-core-breadcrumbs#custom-rendering). Most likely you would want to customize the `RenderSiteLink` method which you can find the default implementation for [here](https://github.com/kentico-ericd/xperience-core-breadcrumbs/blob/a45b6624771484bbb43233509cd8821fa915d83e/Renderer/DefaultBreadcrumbsRenderer.cs#L41).

Though, you could also insert a Home link or any other HTML markup in the `RenderOpeningTag` method as well.
