### ISSUE TITLE
Feature: Customize the Breadcrumb "Name"

### ISSUE THREAD

**Issue by seangwright** [kentico-ericd/xperience-core-breadcrumbs#7]
This project assumes that `DocumentName` is what should be displayed for each page in the breadcrumbs, but Xperience allows for another field to be used as the Name. The name/title could also come from [a value in Custom Data](https://github.com/wiredviews/xperience-page-custom-data-control-extender) for the page.

It would  be nice if the data retrieval/mapping to `BreadcrumbItem` could be customized.

**Comment by kentico-ericd** [comment]
`BreadcrumbItem` generation can now be customized: https://github.com/kentico-ericd/xperience-core-breadcrumbs#breadcrumb-item-generation. Let me know if that's suitable or if you have additional suggestions 👍
