### ISSUE TITLE
Option to include the container (div) html

### ISSUE THREAD

**Issue by wantad** [kentico-ericd/xperience-core-breadcrumbs#9]
fyi...very nicely done. Thanks!

For me, I wanted the option to remove the wrapper (already had legacy html in place from the designers), and this was easy to do, and am passing it along.

In BreadcrumbsWidgetProperties.cs I added:
```

        [EditingComponent(CheckBoxComponent.IDENTIFIER, Order = 7, Label = "Show the html (div) wrapper tags")]
        public bool ShowHtmlWrapper
        {
            get;
            set;
        }
```

Then, in BreadcrumbHelper.cs I changed:
```
                var header = breadcrumbsRenderer.RenderOpeningTag(props.ContainerClass);
                var footer = breadcrumbsRenderer.RenderClosingTag();

```
to 
```
            var header = string.Empty;
            var footer = string.Empty;
            if (props.ShowHtmlWrapper)
            {
                header = breadcrumbsRenderer.RenderOpeningTag(props.ContainerClass);
                footer = breadcrumbsRenderer.RenderClosingTag();
            }

```

Enjoyed the code.  Thanks!

**Comment by kentico-ericd** [comment]
@wantad Glad you like the widget! Just FYI you could accomplish this without modifying the source code as well, using a custom `IBreadcrumbRenderer`. You would just need to alter the `RenderOpeningTag` and `RenderClosingTag` methods, e.g.

```cs
public string RenderOpeningTag(string containerClass)
{
    return "";
}
```

But I understand your approach is more dynamic as it allows you to choose to render the container or not from the admin UI. Thanks for sharing it 👍
